export const LOAD_COINS_LOADING = "LOAD_COINS_LOADING";
export const LOAD_COINS_SUCCESS = "LOAD_COINS_SUCCESS";
export const LOAD_COINS_ERROR = "LOAD_COINS_ERROR";

export const LOAD_COIN_DETAIL_LOADING = "LOAD_COIN_DETAIL_LOADING";
export const LOAD_COIN_DETAIL_SUCCESS = "LOAD_COIN_DETAIL_SUCCESS";
export const LOAD_COIN_DETAIL_ERROR = "LOAD_COIN_DETAIL_ERROR";

export const LOAD_COIN_PRICE_HISTORY_LOADING = "LOAD_COIN_PRICE_HISTORY_LOADING";
export const LOAD_COIN_PRICE_HISTORY_SUCCESSS = "LOAD_COIN_PRICE_HISTORY_SUCCESSS";
export const LOAD_COIN_PRICE_HISTORY_ERROR = "LOAD_COIN_PRICE_HISTORY_ERROR";
